### ISSUE TITLE
Incompatible version of Certbot with conf file 1.30.0 <>1.17.0

### ISSUE THREAD

**Issue by ZarTek-Creole** [leangaurav/nginx_https_docker#4]
docker-compose -f docker-compose-le.yaml up --build

` Attempting to parse the version 1.30.0 renewal configuration file found at /etc/letsencrypt/renewal/my-name.us-0001.conf with version 1.17.0 of Certbot. This might not work.`

**Comment by leangaurav** [comment]
I think the issue is due to the fact that compose file refers to specific version of certbot `1.17.0`.
I'll set this to `latest` to avoid future issues here:
https://github.com/leangaurav/nginx_https_docker/blob/main/docker-compose-le.yaml#L5

**Comment by leangaurav** [comment]
Updated https://github.com/leangaurav/nginx_https_docker/pull/5/commits/618979dcc7d010ac64fb6bab049189589150f5e2
